{{- if (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fsm-gateway-role
  namespace: {{ .Values.gwy.metadata.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-gateway
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}