{{- if and (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) .Values.hasUDP }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "fsm-gateway-%s-%s-udp" .Values.fsm.gateway.namespace .Values.fsm.gateway.name }}
  namespace: {{ .Values.fsm.gateway.namespace }}
  {{- if .Values.fsm.gateway.infrastructure }}
  {{- with .Values.fsm.gateway.infrastructure.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    {{- if .Values.fsm.gateway.infrastructure }}
    {{- with .Values.fsm.gateway.infrastructure.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    app: fsm-gateway
    gateway.flomesh.io/ns: {{ .Values.fsm.gateway.namespace }}
    gateway.flomesh.io/name: {{ .Values.fsm.gateway.name }}
spec:
  type: {{ .Values.fsm.gateway.serviceType }}
  {{- $setNodePorts := (and (eq .Values.fsm.gateway.serviceType "NodePort") .Values.fsm.gateway.nodePorts)}}
  ports:
    {{- range .Values.fsm.gateway.listeners }}
    {{- if eq .protocol "UDP" }}
    {{- $listenerPort := .port }}
    - name: {{ .name }}
      port: {{ $listenerPort }}
      targetPort: {{ $listenerPort }}
      protocol: UDP
      {{- if $setNodePorts }}
      {{- range $.Values.fsm.gateway.nodePorts }}
      {{- if (eq .port $listenerPort) }}
      nodePort: {{ .nodePort }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: fsm-gateway
    gateway.flomesh.io/ns: {{ .Values.fsm.gateway.namespace }}
    gateway.flomesh.io/name: {{ .Values.fsm.gateway.name }}
{{- end }}