{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "fsm-gateway-%s" .Values.gwy.metadata.namespace }}
  namespace: {{ .Values.gwy.metadata.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-gateway
spec:
  type: LoadBalancer
  ports:
    {{- range $listener := .Values.listeners }}
    - name: {{ $listener.name }}
      port: {{ $listener.port }}
      targetPort: {{ ternary (add 60000 $listener.port) $listener.port (lt (int $listener.port) 1024)}}
      protocol: {{ eq $listener.protocol "UDP" | ternary "UDP" "TCP" }}
    {{- end }}
  selector:
    app: fsm-gateway
    gateway.flomesh.io/ns: {{ .Values.gwy.metadata.namespace }}
{{- end }}