// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flomesh-io/fsm/pkg/machine (interfaces: Controller)

// Package machine is a generated GoMock package.
package machine

import (
	reflect "reflect"

	v1alpha1 "github.com/flomesh-io/fsm/pkg/apis/machine/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetVms mocks base method.
func (m *MockController) GetVms() []*v1alpha1.VirtualMachine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVms")
	ret0, _ := ret[0].([]*v1alpha1.VirtualMachine)
	return ret0
}

// GetVms indicates an expected call of GetVms.
func (mr *MockControllerMockRecorder) GetVms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVms", reflect.TypeOf((*MockController)(nil).GetVms))
}
