version: "2"
run:
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - revive
    - whitespace
  disable:
    - errcheck
  settings:
    gosec:
      severity: medium
      confidence: medium
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: dot imports
        source: . "github.com/onsi/(ginkgo|gomega)"
      - linters:
          - revive
        text: dot imports
        source: . "github.com/flomesh-io/fsm/tests/framework"
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - staticcheck
        text: 'ST1001:'
      - linters:
          - staticcheck
        text: 'ST1005:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G115:'
      - linters:
          - staticcheck
        text: 'S1009:'
      - linters:
          - govet
        text: 'printf: non-constant format string in call to'
    paths:
      - zz_generated.deepcopy.go$
      - zz_generated.register.go$
      - pkg/gen
      - pkg/bugreport
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/flomesh-io/fsm
  exclusions:
    generated: lax
    paths:
      - zz_generated.deepcopy.go$
      - zz_generated.register.go$
      - pkg/gen
      - pkg/bugreport
      - third_party$
      - builtin$
      - examples$
