# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: fsm

# Global environment variables for builds.
env:
  - CGO_ENABLED=0
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - make generate-cli-chart

builds:
  # fsm build steps
  - id: fsm
    main: ./cmd/cli
    binary: fsm
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: &build-ldflags
      - -X github.com/flomesh-io/fsm/pkg/version.Version={{ .Env.VERSION }}
      - -X github.com/flomesh-io/fsm/pkg/version.GitCommit={{ .FullCommit }}
      - -X github.com/flomesh-io/fsm/pkg/version.BuildDate={{ .Now.Format "2006-01-02-15:04" }}
      - -s
      - -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64


archives:
  - id: tar-gz
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Env.VERSION }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
  - id: zip
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Env.VERSION }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^revert:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  prerelease: auto
  mode: replace
  replace_existing_artifacts: true
  header: |
    ## {{ tolower .ProjectName }} {{ .Tag }}
    
    Welcome to this new release!
  footer: |
    ## Thanks!
    
    Those were the changes on {{ .Tag }}!

brews:
  - repository:
      owner: flomesh-io
      name: homebrew-fsm
      token: "{{ .Env.HOMEBREW_RELEASE_PAT }}"
    ids:
      - tar-gz
    commit_author:
      name: reaver-flomesh
      email: reaver@flomesh.io
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    goarm: "7"
    homepage: https://flomesh.io/fsm
    description: Lightweight service mesh for Kubernetes East-West and North-South traffic management
    license: Apache 2.0
    test: |
      system "#{bin}/fsm --version"
    dependencies:
      - name: go
        type: optional
      - name: git
        type: optional
