pull_request_rules:
  - name: Automatic squash and merge when CI passes and reviews approve
    conditions:
      - or:
          - base=main
          - base~=^release\/v
      - check-success=DCO
      - check-success=Shellcheck
      - check-success=Lint
      - check-success=Codegen
      - check-success=Go build
      - check-success=Mocks
      - check-success=Chart checks
      - check-success=Go test
      - check-success=Scan images for security vulnerabilities
      - check-success=Integration Test with Tresor, SMI traffic policies, and egress disabled
      - check-success=Go mesh test e2e (1)
      - check-success=Go mesh test e2e (2)
      - check-success=Go mesh test e2e (3)
      - check-success=Go mesh test e2e (4)
      - check-success=Go mesh test e2e (5)
      - check-success=Go mesh test e2e (v1.19.16, Test traffic flowing from client to server with a Kubernetes Service ...
      - check-success=Go mesh test e2e (v1.27.11, Test traffic flowing from client to server with a Kubernetes Service ...
      - check-success=Go gateway test e2e (6)
      - check-success=Go gateway test e2e (v1.19.16, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go gateway test e2e (v1.21.14, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go gateway test e2e (v1.23.17, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go ingress test e2e (7)
      - check-success=Go statefulset test e2e (8)
      - check-success=Go retry test e2e (9)
      - "#approved-reviews-by >= 1"
      - or:
          - and:
            - label=ok-to-merge
            - label=squash
          - label=ok-to-squash
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: squash
  - name: Rebase pull request when it's more than 3 commits behind main
    conditions:
      - base = main
      - "#commits-behind >= 3"
    actions:
      rebase:
  - name: Backport features/patches to the release/v1.4 branch
    conditions:
      - base=main
      - label = backport/v1.4
    actions:
      backport:
        branches:
          - "release/v1.4"
        title: "[backport] {{ title }} (#{{ number }})"
        assignees:
          - "{{ author }}"
  - name: Backport features/patches to the release/v1.3 branch
    conditions:
      - base=main
      - label = backport/v1.3
    actions:
      backport:
        branches:
          - "release/v1.3"
        title: "[backport] {{ title }} (#{{ number }})"
        assignees:
          - "{{ author }}"
  - name: Backport features/patches to the release/v1.2 branch
    conditions:
      - base=main
      - label = backport/v1.2
    actions:
      backport:
        branches:
          - "release/v1.2"
        title: "[backport] {{ title }} (#{{ number }})"
        assignees:
          - "{{ author }}"
  - name: Cherry-pick patches from release/v* to the main branch
    conditions:
      - base~=^release\/v
      - label = cherry-pick/main
    actions:
      backport:
        branches:
          - main
        title: "[cherry-pick] {{ title }} (#{{ number }})"
        assignees:
          - "{{ author }}"
  - name: Ping PR author when conflicting and Label conflicting pull requests
    description: Warn the pull request author when their PR are conflicting, and add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be merged
      label:
        toggle:
          - conflicts
  - name: Comment when a pull request has unverified commits
    conditions:
      - -closed
      - "#commits-unverified > 0"
    actions:
      comment:
        message: |
          ❗❗❗
          All commits in this PR must be signed off. 
          Please sign all commits by:
          
          ```shell
          git rebase HEAD~{{ commits | length }} --signoff
          git push --force-with-lease origin {{ head }}
          ```
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - or:
        - base=main
        - base~=^release\/v
    success_conditions:
      - "title ~= ^(\\[wip\\]|\\[backport\\]|\\[cherry-pick\\])?(
        )?(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Enforce verified commits
    description: Make sure that we have verified commits
    if:
      - or:
        - base=main
        - base~=^release\/v
    success_conditions:
      - "#commits-unverified = 0"
  - name: Enforce linear history
    description: Make sure that we have a linear history, no merge commits are allowed
    if:
      - or:
        - base=main
        - base~=^release\/v
    success_conditions:
      - "linear-history"

