pull_request_rules:
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
  - name: Automatic squash and merge when CI passes and reviews approve
    conditions:
      - or:
          - base=main
          - base~=^release\/v
      - check-success=DCO
      - check-success=Shellcheck
      - check-success=Lint
      - check-success=Codegen
      - check-success=Go build
      - check-success=Mocks
      - check-success=Chart checks
      - check-success=Go test
      - check-success=Scan images for security vulnerabilities
      - check-success=Integration Test with Tresor, SMI traffic policies, and egress disabled
      - check-success=Go mesh test e2e (1)
      - check-success=Go mesh test e2e (2)
      - check-success=Go mesh test e2e (3)
      - check-success=Go mesh test e2e (4)
      - check-success=Go mesh test e2e (5)
      - check-success=Go mesh test e2e (v1.19.16, Test traffic flowing from client to server with a Kubernetes Service ...
      - check-success=Go mesh test e2e (v1.27.11, Test traffic flowing from client to server with a Kubernetes Service ...
      - check-success=Go gateway test e2e (6)
      - check-success=Go gateway test e2e (v1.19.16, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go gateway test e2e (v1.21.14, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go gateway test e2e (v1.23.17, Test traffic from client to backend service routing by FSM Gateway...
      - check-success=Go ingress test e2e (7)
      - check-success=Go statefulset test e2e (8)
      - check-success=Go retry test e2e (9)
      - "#approved-reviews-by >= 1"
      - label=auto-squash
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: squash
  - name: Rebase pull request when it's more than 3 commits behind main
    conditions:
      - base = main
      - "#commits-behind >= 3"
    actions:
      rebase:
  - name: Add a label auto-squash to the PR automatically
    conditions:
      - -closed
      - -label=wip
      - -label=do-not-merge/hold
      - -label=auto-merge
      - -label=auto-rebase
    actions:
      label:
        add:
          - auto-squash
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
  - name: Backport features/patches to the release/v1.4 branch
    conditions:
      - base=main
      - label = backport/v1.4
    actions:
      backport:
        branches:
          - "release/v1.4"
        title: "[backport] {{ title }}"
        assignees:
          - "{{ author }}"
  - name: Backport features/patches to the release/v1.3 branch
    conditions:
      - base=main
      - label = backport/v1.3
    actions:
      backport:
        branches:
          - "release/v1.3"
        title: "[backport] {{ title }}"
        assignees:
          - "{{ author }}"
  - name: Backport features/patches to the release/v1.2 branch
    conditions:
      - base=main
      - label = backport/v1.2
    actions:
      backport:
        branches:
          - "release/v1.2"
        title: "[backport] {{ title }}"
        assignees:
          - "{{ author }}"
  - name: Cherry-pick patches from release/v* to the main branch
    conditions:
      - base~=^release\/v
      - label = cherry-pick/main
    actions:
      backport:
        branches:
          - main
        title: "[cherry-pick] {{ title }}"
        assignees:
          - "{{ author }}"
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - or:
        - base=main
        - base~=^release\/v
    success_conditions:
      - "title ~= ^(\\[wip\\]|\\[backport\\]|\\[cherry-pick\\])?(
        )?(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"

