pull_request_rules:
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
  - name: Automatic squash and merge when CI passes and reviews approve
    conditions:
      - or:
          - base=main
          - base~=^release\/v
      - check-success=DCO
      - check-success=Shellcheck
      - check-success=Lint
      - check-success=Codegen
      - check-success=Go build
      - check-success=Mocks
      - check-success=Chart checks
      - check-success=Go test
      - check-success=Scan images for security vulnerabilities
      - check-success=Integration Test with Tresor, SMI traffic policies, and
        egress disabled
      - check-success=Go mesh test e2e (1)
      - check-success=Go mesh test e2e (2)
      - check-success=Go mesh test e2e (3)
      - check-success=Go mesh test e2e (4)
      - check-success=Go mesh test e2e (5)
      - "check-success=Go mesh test e2e (v1.19.16, Test traffic flowing from
        client to server with a Kubernetes Service for the Source: HTTP)"
      - "check-success=Go mesh test e2e (v1.27.11, Test traffic flowing from
        client to server with a Kubernetes Service for the Source: HTTP)"
      - check-success=Go gateway test e2e (6)
      - check-success=Go gateway test e2e (v1.19.16, Test traffic from client to
        backend service routing by FSM Gateway)
      - check-success=Go gateway test e2e (v1.21.14, Test traffic from client to
        backend service routing by FSM Gateway)
      - check-success=Go gateway test e2e (v1.23.17, Test traffic from client to
        backend service routing by FSM Gateway)
      - check-success=Go ingress test e2e (7)
      - check-success=Go statefulset test e2e (8)
      - check-success=Go retry test e2e (9)
      - "#approved-reviews-by >= 1"
      - label=auto-squash
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: squash
