package metricsstore

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	tassert "github.com/stretchr/testify/assert"

	"github.com/flomesh-io/fsm/pkg/constants"
)

func setup() {
	DefaultMetricsStore.Start(
		DefaultMetricsStore.K8sAPIEventCounter,
		DefaultMetricsStore.ProxyConnectCount,
		DefaultMetricsStore.ErrCodeCounter,
	)
}

func teardown() {
	DefaultMetricsStore.Stop(
		DefaultMetricsStore.K8sAPIEventCounter,
		DefaultMetricsStore.ProxyConnectCount,
		DefaultMetricsStore.ErrCodeCounter,
	)
}

func TestMetricsStore(t *testing.T) {
	setup()
	defer teardown()

	t.Run("K8sAPIEventCounter", func(t *testing.T) {
		assert := tassert.New(t)

		apiEventCount := 3

		for i := 1; i <= apiEventCount; i++ {
			DefaultMetricsStore.K8sAPIEventCounter.WithLabelValues("add", "foo").Inc()

			handler := DefaultMetricsStore.Handler()

			req, err := http.NewRequest("GET", constants.MetricsPath, nil)
			assert.Nil(err)

			rr := httptest.NewRecorder()
			handler.ServeHTTP(rr, req)

			assert.Equal(http.StatusOK, rr.Code)

			expectedResp := fmt.Sprintf(`# HELP fsm_k8s_api_event_count Represents the number of events received from the Kubernetes API Server
# TYPE fsm_k8s_api_event_count counter
fsm_k8s_api_event_count{namespace="foo",type="add"} %d
`, i /* api event count */)
			assert.Contains(rr.Body.String(), expectedResp)
		}
	})

	t.Run("ProxyConnectCount", func(t *testing.T) {
		assert := tassert.New(t)

		proxiesConnected := 5
		proxiesDisconnected := 2

		for i := 1; i <= proxiesConnected; i++ {
			DefaultMetricsStore.ProxyConnectCount.Inc()
		}
		for i := 1; i <= proxiesDisconnected; i++ {
			DefaultMetricsStore.ProxyConnectCount.Dec()
		}

		handler := DefaultMetricsStore.Handler()

		req, err := http.NewRequest("GET", "/metrics", nil)
		assert.Nil(err)

		rr := httptest.NewRecorder()
		handler.ServeHTTP(rr, req)

		assert.Equal(http.StatusOK, rr.Code)

		expectedResp := fmt.Sprintf(`# HELP fsm_proxy_connect_count Represents the number of proxies connected to FSM controller
# TYPE fsm_proxy_connect_count gauge
fsm_proxy_connect_count %d
`, proxiesConnected-proxiesDisconnected)
		assert.Contains(rr.Body.String(), expectedResp)
	})

	t.Run("ErrcodeCounter", func(t *testing.T) {
		assert := tassert.New(t)

		errcodeCount := 3

		for i := 1; i <= errcodeCount; i++ {
			DefaultMetricsStore.ErrCodeCounter.WithLabelValues("E1100").Inc()

			handler := DefaultMetricsStore.Handler()

			req, err := http.NewRequest("GET", constants.MetricsPath, nil)
			assert.Nil(err)

			rr := httptest.NewRecorder()
			handler.ServeHTTP(rr, req)

			assert.Equal(http.StatusOK, rr.Code)

			expectedResp := fmt.Sprintf(`# HELP fsm_error_err_code_count Respesents the number of errcodes generated by FSM
# TYPE fsm_error_err_code_count counter
fsm_error_err_code_count{err_code="E1100"} %d
`, i /* api event count */)
			assert.Contains(rr.Body.String(), expectedResp)
		}
	})
}

func TestConnectorMetrics(t *testing.T) {
	DefaultMetricsStore.Start(
		DefaultMetricsStore.ConnectorSyncReady,
		DefaultMetricsStore.ConnectorSyncOperations,
	)
	defer DefaultMetricsStore.Stop(
		DefaultMetricsStore.ConnectorSyncReady,
		DefaultMetricsStore.ConnectorSyncOperations,
	)

	DefaultMetricsStore.ConnectorSyncReady.WithLabelValues("cloud_to_k8s").Set(1)
	DefaultMetricsStore.ConnectorSyncOperations.WithLabelValues("cloud_to_k8s", "catalog_list", "success").Inc()

	assert := tassert.New(t)
	assert.True(DefaultMetricsStore.Contains("fsm_connector_sync_ready{direction=\"cloud_to_k8s\"} 1\n"))
	assert.True(DefaultMetricsStore.Contains("fsm_connector_sync_operations_total{direction=\"cloud_to_k8s\",operation=\"catalog_list\",result=\"success\"} 1\n"))
}
