{
 "title": "FSM Data Plane Performance Metrics",
 "description": "Compatible with FSM v1.0.0. This dashboard lets you view the performance of FSM’s data plane.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(source_namespace)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(sidecar_server_live{source_namespace=~\"$namespace\"}, source_pod_name)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(sidecar_server_live{source_namespace=~\"$namespace\", source_pod_name=~\"$pod\"}, source_workload_name)"
   }
  ]
 },
 "panels": [
  { "title": "Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sidecar CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"sidecar\"}[1m])",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Sidecar RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=~\"$namespace\", pod=~\"$pod\", container=\"sidecar\"}",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Other containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Container RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  }
 ]
}