{
 "title": "FSM Mesh and Pipy Details",
 "description": "Compatible with FSM v1.0.0. This dashboard lets you view the performance and behavior of FSM’s control plane.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "fsm_controller_instance",
    "label": "FSM Controller instance",
    "query": "label_values(fsm_proxy_connect_count, source_pod_name)"
   },
   {
    "name": "fsm_injector_instance",
    "label": "FSM Injector instance",
    "query": "label_values(fsm_cert_issued_count, source_pod_name)"
   },
   {
    "name": "xds_path",
    "label": "xDS Path",
    "query": "label_values(fsm_proxy_config_update_time_bucket, resource_type)"
   },
   {
    "name": "fsm_error_code",
    "label": "FSM Error Code",
    "query": "label_values(fsm_error_err_code_count, err_code)"
   }
  ]
 },
 "panels": [
  { "title": "Mesh Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored Namespace Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fsm_resource_namespace_count{source_pod_name=~\"$fsm_controller_instance\"}) by (source_pod_name)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Connected Proxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsm_proxy_connect_count{source_pod_name=~\"$fsm_controller_instance\"}",
     "legendFormat": "Connected proxies"
    }
   ]
  },
  {
   "title": "Control plane resource consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"${CONTROL_PLANE_NAMESPACE}\", container!~\"POD\", container!~\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory footprint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"${CONTROL_PLANE_NAMESPACE}\", container!=\"\", container!=\"POD\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "FSM Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Sidecar injector timings (sec) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(fsm_http_response_duration_bucket{method=\"post\",path=\"/mutate-pod-creation\",source_pod_name=~\"$fsm_injector_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Certificate Issue timings (sec) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(fsm_cert_issued_time_bucket{source_pod_name=~\"$fsm_injector_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sidecar injector timings (sec) - Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fsm_http_response_duration_bucket{method=\"post\",path=\"/mutate-pod-creation\",source_pod_name=~\"$fsm_injector_instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Certificate Issue timings (sec) - Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fsm_cert_issued_time_bucket{source_pod_name=~\"$fsm_injector_instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "xDS Path histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(fsm_proxy_config_update_time_bucket{resource_type=\"$xds_path\", source_pod_name=~\"$fsm_controller_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Injector Webhooks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "irate(fsm_admission_webhook_response_total{kind=\"Pod\",success=\"true\",source_pod_name=~\"$fsm_injector_instance\"}[1m])\n",
     "legendFormat": "Success"
    },
    {
     "expr": "irate(fsm_admission_webhook_response_total{kind=\"Pod\",success=\"false\",source_pod_name=~\"$fsm_injector_instance\"}[1m])\n",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "xDS Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "idelta(fsm_proxy_config_update_time_count{success=\"true\", resource_type=~\"$xds_path\", source_pod_name=~\"$fsm_controller_instance\"}[1m])\n",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Success"
    },
    {
     "expr": "idelta(fsm_proxy_config_update_time_count{success=\"false\", resource_type=~\"$xds_path\", source_pod_name=~\"$fsm_controller_instance\"}[1m])",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Failure"
    }
   ]
  },
  { "title": "FSM Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Rate of Increase of FSM Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fsm_error_err_code_count{source_pod_name=~\"$fsm_controller_instance\",err_code=~\"$fsm_error_code\"}[1m])",
     "legendFormat": "{{source_pod_name}}"
    },
    {
     "expr": "rate(fsm_error_err_code_count{source_pod_name=~\"$fsm_injector_instance\",err_code=~\"$fsm_error_code\"}[1m])",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "FSM Controller Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(fsm_error_err_code_count{source_pod_name=~\"$fsm_controller_instance\",err_code=~\"$fsm_error_code\"}[1m])\n",
     "legendFormat": "{{err_code}}, {{source_pod_name}}"
    }
   ]
  },
  {
   "title": "FSM Injector Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(fsm_error_err_code_count{source_pod_name=~\"$fsm_injector_instance\",err_code=~\"$fsm_error_code\"}[1m])",
     "legendFormat": "{{err_code}}, {{source_pod_name}}"
    }
   ]
  }
 ]
}