{
 "title": "FSM Workload to Service Metrics",
 "description": "Compatible with FSM v1.0.0. This dashboard provides the traffic metrics from a workload (deployment, replicaSet) to all the services it connects/talks to.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_namespace",
    "label": "Source Namespace",
    "query": "label_values(sidecar_server_live{}, source_namespace)"
   },
   {
    "name": "source_workload_kind",
    "label": "Source Workload Kind",
    "query": "label_values(sidecar_server_live{source_namespace=\"$source_namespace\"}, source_workload_kind)"
   },
   {
    "name": "source_workload_name",
    "label": "Source Workload Name",
    "query": "label_values(sidecar_server_live{source_namespace=\"$source_namespace\", source_workload_kind=\"$source_workload_kind\"}, source_workload_name)"
   }
  ]
 },
 "panels": [
  { "title": "Request Count - HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Count to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class=\"2\",source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Failure Count to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class!=\"2\",source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Connections to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sidecar_cluster_upstream_cx_active{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection/Requests errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_destroy_remote_with_active_rq{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection destroyed by the client - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_cx_connect_timeout{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection timeout - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_cx_destroy_local_with_active_rq{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection destroyed by local Sidecar - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_pending_failure_eject{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Pending failure ejection - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_pending_overflow{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Pending overflow - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_timeout{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Request timeout - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_rx_reset{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Response reset - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_tx_reset{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Request reset - {{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_rx_bytes_total{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_tx_bytes_total{source_namespace=\"$source_namespace\",source_workload_kind=\"$source_workload_kind\",source_workload_name=\"$source_workload_name\",sidecar_cluster_name!~\"fsm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  }
 ]
}