// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flomesh-io/fsm/pkg/xnetwork (interfaces: Controller)

// Package xnetwork is a generated GoMock package.
package xnetwork

import (
	reflect "reflect"

	v1alpha1 "github.com/flomesh-io/fsm/pkg/apis/xnetwork/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetAccessControls mocks base method.
func (m *MockController) GetAccessControls() []*v1alpha1.AccessControl {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessControls")
	ret0, _ := ret[0].([]*v1alpha1.AccessControl)
	return ret0
}

// GetAccessControls indicates an expected call of GetAccessControls.
func (mr *MockControllerMockRecorder) GetAccessControls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessControls", reflect.TypeOf((*MockController)(nil).GetAccessControls))
}
