// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flomesh-io/fsm/pkg/plugin (interfaces: Controller)

// Package plugin is a generated GoMock package.
package plugin

import (
	reflect "reflect"

	v1alpha1 "github.com/flomesh-io/fsm/pkg/apis/plugin/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetPluginChains mocks base method.
func (m *MockController) GetPluginChains() []*v1alpha1.PluginChain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPluginChains")
	ret0, _ := ret[0].([]*v1alpha1.PluginChain)
	return ret0
}

// GetPluginChains indicates an expected call of GetPluginChains.
func (mr *MockControllerMockRecorder) GetPluginChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginChains", reflect.TypeOf((*MockController)(nil).GetPluginChains))
}

// GetPluginConfigs mocks base method.
func (m *MockController) GetPluginConfigs() []*v1alpha1.PluginConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPluginConfigs")
	ret0, _ := ret[0].([]*v1alpha1.PluginConfig)
	return ret0
}

// GetPluginConfigs indicates an expected call of GetPluginConfigs.
func (mr *MockControllerMockRecorder) GetPluginConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginConfigs", reflect.TypeOf((*MockController)(nil).GetPluginConfigs))
}

// GetPlugins mocks base method.
func (m *MockController) GetPlugins() []*v1alpha1.Plugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlugins")
	ret0, _ := ret[0].([]*v1alpha1.Plugin)
	return ret0
}

// GetPlugins indicates an expected call of GetPlugins.
func (mr *MockControllerMockRecorder) GetPlugins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlugins", reflect.TypeOf((*MockController)(nil).GetPlugins))
}
