# syntax = docker/dockerfile:1.4
ARG GO_VERSION
FROM --platform=$BUILDPLATFORM golang:$GO_VERSION AS builder
ARG LDFLAGS
ARG TARGETOS
ARG TARGETARCH

WORKDIR /fsm
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v -o fsm-xnet-mgmt -ldflags "$LDFLAGS" ./cmd/fsm-xnetmgmt

#FROM gcr.io/distroless/static
FROM ubuntu:22.04

# fix CVE-2025-0395
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get purge --auto-remove && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=builder /fsm/fsm-xnet-mgmt /