# syntax = docker/dockerfile:1
ARG GO_VERSION
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION:-latest} AS builder
ARG LDFLAGS
ARG TARGETOS
ARG TARGETARCH
ARG GOPROXY
ARG GOSUMDB
ARG HTTPS_PROXY
ARG HTTP_PROXY
ARG NO_PROXY
ARG GONOSUMCHECK
ARG GONOSUMDB
ARG GOFLAGS

ENV GOPROXY=${GOPROXY} \
    GOSUMDB=${GOSUMDB} \
    GONOSUMCHECK=${GONOSUMCHECK} \
    GONOSUMDB=${GONOSUMDB} \
    HTTPS_PROXY=${HTTPS_PROXY} \
    HTTP_PROXY=${HTTP_PROXY} \
    NO_PROXY=${NO_PROXY} \
    GOFLAGS=${GOFLAGS}

WORKDIR /fsm
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v -o fsm-controller -ldflags "$LDFLAGS" ./cmd/fsm-controller

FROM gcr.io/distroless/static
COPY --from=builder /fsm/fsm-controller /