ARG GO_VERSION
FROM --platform=$BUILDPLATFORM golang:$GO_VERSION AS builder
ARG TARGETOS
ARG TARGETARCH
ARG BINARY

WORKDIR /fsm
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v ./demo/cmd/$BINARY

FROM gcr.io/distroless/base AS final-linux
FROM final-$TARGETOS
ARG BINARY
COPY --from=builder /fsm/$BINARY* /
