# syntax = docker/dockerfile:1
ARG GO_VERSION
ARG DISTROLESS_TAG

# Build the fsm-gateway binary
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION:-latest} AS builder
ARG LDFLAGS
ARG TARGETOS
ARG TARGETARCH
ARG GOPROXY
ARG GOSUMDB
ARG HTTPS_PROXY
ARG HTTP_PROXY
ARG NO_PROXY
ARG GONOSUMCHECK
ARG GONOSUMDB
ARG GOFLAGS

ENV GOPROXY=${GOPROXY} \
    GOSUMDB=${GOSUMDB} \
    GONOSUMCHECK=${GONOSUMCHECK} \
    GONOSUMDB=${GONOSUMDB} \
    HTTPS_PROXY=${HTTPS_PROXY} \
    HTTP_PROXY=${HTTP_PROXY} \
    NO_PROXY=${NO_PROXY} \
    GOFLAGS=${GOFLAGS}

WORKDIR /fsm
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN --mount=type=cache,target=/go/pkg go mod download
# Copy the go source
COPY . .

# Build
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v -o bin/fsm-gateway -ldflags "$LDFLAGS" ./cmd/fsm-gateway

# Build the final image
FROM flomesh/pipy:1.5.14-$DISTROLESS_TAG
WORKDIR /
COPY --from=builder /fsm/bin/fsm-gateway .

USER 65532:65532

ENTRYPOINT ["/fsm-gateway"]
