# syntax = docker/dockerfile:1.4
ARG DISTROLESS_TAG
ARG PIPY_VERSION

# Build the pipy binary
FROM --platform=$BUILDPLATFORM flomesh/pipy:${PIPY_VERSION}-debian AS builder

# Build the final image
FROM --platform=$BUILDPLATFORM gcr.io/distroless/cc-debian12:$DISTROLESS_TAG
WORKDIR /
COPY --from=builder /usr/local/bin/pipy /usr/local/bin/pipy

USER 65532:65532
EXPOSE 6060
STOPSIGNAL SIGQUIT

ENTRYPOINT ["/usr/local/bin/pipy"]
