{{- if .Values.fsm.egressGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fsm-egress-gateway
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-egress-gateway
    meshName: {{ .Values.fsm.meshName }}
  annotations:
    flomesh.io/egress-gateway-mode: {{ .Values.fsm.egressGateway.mode }}
spec:
  ports:
    - port: {{ .Values.fsm.egressGateway.port }}
      name: egress-nat-port
      targetPort: {{ .Values.fsm.egressGateway.port }}
      protocol: TCP
      appProtocol: tcp
  selector:
    app: fsm-egress-gateway
{{- end }}