{{- if .Values.fsm.egressGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fsm.egressGateway.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-egress-gateway
    meshName: {{ .Values.fsm.meshName }}
spec:
  replicas: {{ .Values.fsm.egressGateway.replicaCount }}
  selector:
    matchLabels:
      app: fsm-egress-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
        app: fsm-egress-gateway
        {{- with .Values.fsm.egressGateway.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/path: '/stats/prometheus'
        prometheus.io/port: '15010'
        prometheus.io/scrape: 'true'
        {{- with .Values.fsm.egressGateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: pipy
        image: "{{ include "repoServer.image" . }}"
        imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
        resources:
          {{- toYaml .Values.fsm.egressGateway.resources | nindent 10 }}
        volumeMounts:
          - name:  fsm-egress-gateway-pjs
            mountPath: "/repo/egress-gateway.js"
            subPath: egress-gateway.js
            readOnly: true
        ports:
          - name: "egress-nat-port"
            containerPort: {{ .Values.fsm.egressGateway.port }}
          - name: "pipy-admin-port"
            containerPort: {{ .Values.fsm.egressGateway.adminPort }}
        command:
          - pipy
        args:
          - "/repo/egress-gateway.js"
          - "--log-level={{ .Values.fsm.egressGateway.logLevel }}"
          - "--admin-port={{ .Values.fsm.egressGateway.adminPort }}"
        env:
          - name: FSM_NAMESPACE
            value: {{ include "fsm.namespace" . }}
          - name: FSM_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: FSM_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
        - name:  fsm-egress-gateway-pjs
          configMap:
            name:  fsm-egress-gateway-pjs
      serviceAccountName: {{ .Release.Name }}
      {{- with .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}