{{- if not .Values.fsm.repo.preProvision.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "fsm.namespace" . }}
  name: {{ .Values.fsm.flb.secretName }}
  labels:
    flb.flomesh.io/config: "true"
type: Opaque
data:
  baseUrl: {{ .Values.fsm.flb.baseUrl | b64enc }}
  username: {{ .Values.fsm.flb.username | b64enc }}
  password: {{ .Values.fsm.flb.password | b64enc }}
  defaultCluster: {{ .Values.fsm.flb.defaultCluster | b64enc }}
  defaultAddressPool: {{ .Values.fsm.flb.defaultAddressPool | b64enc }}
  defaultAlgo: {{ .Values.fsm.flb.defaultAlgo | b64enc }}
{{- end }}