{{- if .Values.fsm.cloudConnector.gateway.syncToFgw.enable }}
{{- if .Values.fsm.injector.enablePodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: fsm-gateway-connector-pdb
  namespace: {{ include "fsm.namespace" . }}
  labels:
    app: fsm-gateway-connector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fsm-gateway-connector
{{- end }}
{{- end }}