{{- if .Values.fsm.logging.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "fsm.namespace" . }}
  name: {{ .Values.fsm.logging.secretName }}
type: Opaque
data:
  url: {{ .Values.fsm.logging.url | b64enc }}
  token: {{ .Values.fsm.logging.token | b64enc }}
{{- end }}