apiVersion: v1
kind: Service
metadata:
  name: fsm-controller
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-controller
spec:
  ports:
    - name: pipy-admin-port
      port: {{ .Values.fsm.repoServer.port }}
      targetPort: {{ .Values.fsm.repoServer.port }}
    - name: debug-port
      port: 9092
      targetPort: 9092
    - name: healthz
      port: 9091
      targetPort: 9091
    - name: webhook
      port: 9443
      targetPort: 9443
  selector:
    app: fsm-controller
