{{- if .Values.fsm.cloudConnector.machine.enable }}
apiVersion: v1
kind: Service
metadata:
  name: fsm-machine-connector
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-machine-connector
spec:
  ports:
    - name: machine-connector
      port: 9090
  selector:
    app: fsm-machine-connector
{{- end }}