{{- if and .Values.fsm.ingress.enabled (not .Values.fsm.gatewayApi.enabled ) (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: pipy
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    meta.flomesh.io/namespace: {{ include "fsm.namespace" . }}
    meta.flomesh.io/ingress-pipy-svc: {{ .Values.fsm.ingress.service.name }}
spec:
  controller: flomesh.io/ingress-pipy
{{- end }}