apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-injector
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-injector
    meshName: {{ .Values.fsm.meshName }}
spec:
  {{- if not .Values.fsm.injector.autoScale.enable }}
  replicas: {{ .Values.fsm.injector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: fsm-injector
  template:
    metadata:
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
        app: fsm-injector
  {{- if .Values.fsm.injector.podLabels }}
  {{- toYaml .Values.fsm.injector.podLabels | nindent 8 }}
  {{- end }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
    spec:
      {{- if .Values.fsm.injector.affinity }}
      affinity:
      {{- toYaml .Values.fsm.injector.affinity | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      serviceAccountName: {{ .Release.Name }}
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      initContainers:
        - name: init-fsm-injector
          image: "{{ include "fsmCurl.image" . }}"
          command: ["curl", "http://fsm-bootstrap.{{ include "fsm.namespace" . }}:9091/healthz", "--connect-timeout", "2", "--retry", "50", "--retry-connrefused", "--retry-delay", "5"]
          resources:
            {{- toYaml .Values.fsm.injector.initResources | nindent 12 }}
      containers:
        - name: fsm-injector
          image: "{{ include "fsmInjector.image" . }}"
          imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
          ports:
            - name: "sidecar-inject"
              containerPort: 9090
            - name: "metrics"
              containerPort: 9091
          command: ['/fsm-injector']
          args: [
            "--verbosity", "{{.Values.fsm.controllerLogLevel}}",
            "--fsm-namespace", "{{ include "fsm.namespace" . }}",
            "--fsm-version", "{{ .Chart.AppVersion }}",
            "--mesh-name", "{{.Values.fsm.meshName}}",
            "--webhook-config-name", "{{.Values.fsm.webhookConfigNamePrefix}}-{{.Values.fsm.meshName}}",
            "--webhook-timeout", "{{.Values.fsm.injector.webhookTimeoutSeconds}}",
            "--ca-bundle-secret-name", "{{.Values.fsm.caBundleSecretName}}",
            "--certificate-manager", "{{.Values.fsm.certificateProvider.kind}}",
            "--trust-domain", "{{.Values.fsm.trustDomain}}",
            "--enable-mesh-root-certificate={{.Values.fsm.featureFlags.enableMeshRootCertificate}}",
            {{ if eq .Values.fsm.certificateProvider.kind "vault" }}
            "--vault-host", "{{.Values.fsm.vault.host}}",
            "--vault-port", "{{.Values.fsm.vault.port}}",
            "--vault-protocol", "{{.Values.fsm.vault.protocol}}",
            "--vault-token", "{{.Values.fsm.vault.token}}",
            "--vault-token-secret-name",  "{{ .Values.fsm.vault.secret.name }}",
            "--vault-token-secret-key",  "{{ .Values.fsm.vault.secret.key }}",
            {{- end }}
            "--cert-manager-issuer-name", "{{.Values.fsm.certmanager.issuerName}}",
            "--cert-manager-issuer-kind", "{{.Values.fsm.certmanager.issuerKind}}",
            "--cert-manager-issuer-group", "{{.Values.fsm.certmanager.issuerGroup}}",
            "--enable-reconciler={{.Values.fsm.enableReconciler}}",
            "--fsm-container-pull-policy={{.Values.fsm.image.pullPolicy}}",
          ]
          resources:
            limits:
              cpu: "{{.Values.fsm.injector.resource.limits.cpu}}"
              memory: "{{.Values.fsm.injector.resource.limits.memory}}"
            requests:
              cpu: "{{.Values.fsm.injector.resource.requests.cpu}}"
              memory: "{{.Values.fsm.injector.resource.requests.memory}}"
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 9091
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 9091
          env:
            - name: CONTROLLER_SVC_NAME
              value: fsm-controller
            # The INJECTOR_POD_NAME env variable sets pod name dynamically, used by fsm-injector to register events
            - name: INJECTOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FSM_DEFAULT_SIDECAR_IMAGE
              value: '{{ include "sidecar.image" . }}'
            - name: FSM_DEFAULT_INIT_CONTAINER_IMAGE
              value: '{{ include "fsmSidecarInit.image" . }}'
            - name: FSM_DEFAULT_HEALTHCHECK_CONTAINER_IMAGE
              value: '{{ include "fsmHealthcheck.image" . }}'
    {{- if .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.fsm.imagePullSecrets | indent 8 }}
    {{- end }}
      {{- if .Values.fsm.injector.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.injector.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.injector.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.injector.tolerations | nindent 8 }}
      {{- end }}
