{{- if .Values.fsm.deployGrafana}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-grafana
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsm-grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
        app: fsm-grafana
    spec:
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: fsm-grafana
      containers:
        - name: grafana
          image: "{{ include "grafana.image" . }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 128M
            requests:
              cpu: 100m
              memory: 64M
          volumeMounts:
            - name: fsm-grafana-config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: fsm-grafana-storage
              mountPath: "/var/lib/grafana"
            - name: fsm-grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: fsm-grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: fsm-grafana-dashboard-definition-controlplane
              mountPath: /etc/grafana/provisioning/dashboards/controlplane
              readOnly: true
            - name: fsm-grafana-dashboard-definition-dataplane
              mountPath: /etc/grafana/provisioning/dashboards/dataplane
              readOnly: true
          ports:
            - containerPort: {{.Values.fsm.grafana.port}}
{{- if .Values.fsm.grafana.enableRemoteRendering}}
          env:
          - name: GF_RENDERING_SERVER_URL
            value: "http://fsm-grafana:8081/render"
          - name: GF_RENDERING_CALLBACK_URL
            value: "http://fsm-grafana:3000/"
          - name: GF_LOG_FILTERS
            value: "rendering:debug"
        - name: renderer
          image: "{{ include "grafana.renderer.image" . }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 256M
            requests:
              cpu: 100m
              memory: 64M
          ports:
            - containerPort: 8081
          env:
          - name: ENABLE_METRICS
            value: "true"
          - name: RENDERING_MODE
            value: "clustered"
          - name: RENDERING_CLUSTERING_MODE
            value: "context"
          - name: RENDERING_CLUSTERING_MAX_CONCURRENCY
            value: "5"
{{- end }}
      volumes:
        - name: fsm-grafana-config
          configMap:
            name: fsm-grafana-config
        - name: fsm-grafana-datasources
          configMap:
            name: fsm-grafana-datasources
        - name: fsm-grafana-dashboards
          configMap:
            name: fsm-grafana-dashboards
        - name: fsm-grafana-dashboard-definition-controlplane
          configMap:
            name: fsm-grafana-dashboard-definition-controlplane
        - name: fsm-grafana-dashboard-definition-dataplane
          configMap:
            name: fsm-grafana-dashboard-definition-dataplane
        - name: fsm-grafana-storage
          emptyDir: {}
      {{- if .Values.fsm.grafana.affinity }}
      affinity:
      {{- toYaml .Values.fsm.grafana.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.grafana.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.grafana.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.grafana.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.grafana.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
