{{- if .Values.fsm.deployPrometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-prometheus
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fsm-prometheus
  template:
    metadata:
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
        app: fsm-prometheus
    spec:
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      containers:
      - name: prometheus
        ports:
        - containerPort: {{.Values.fsm.prometheus.port}}
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --storage.tsdb.retention.time={{.Values.fsm.prometheus.retention.time}}
        - --web.listen-address=:{{.Values.fsm.prometheus.port}}
        image: "{{ include "prometheus.image" . }}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "{{.Values.fsm.prometheus.resources.limits.cpu}}"
            memory: "{{.Values.fsm.prometheus.resources.limits.memory}}"
          requests:
            cpu: "{{.Values.fsm.prometheus.resources.requests.cpu}}"
            memory: "{{.Values.fsm.prometheus.resources.requests.memory}}"
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      serviceAccountName: fsm-prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: fsm-prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
      {{- if .Values.fsm.prometheus.affinity }}
      affinity:
      {{- toYaml .Values.fsm.prometheus.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.prometheus.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.prometheus.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.prometheus.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.prometheus.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
