{{- if (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fsm.namespaced-ingress.serviceAccountName" . }}
  namespace: {{ .Values.nsig.metadata.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-ingress
{{- end }}
