name: Grant execute permission to fsm CLI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      bin_path:
        required: true
        type: string

jobs:
  grant-execute-permission:
    name: fsm-cli
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        run: |
          os=$(uname -s)
          if [[ "${os}" = "Darwin" ]]; then
            export OS="darwin"
          elif [[ "${os}" = "Linux" ]]; then
            export OS="linux"
          else
            echo "Unsupported OS: ${OS}"
            exit 1
          fi
          
          arch=$(uname -m)
          if [[ "${arch}" = "x86_64" ]; then
            export ARCH="amd64"
          elif [[ "${arch}" = "aarch64" ]]; then
            export ARCH="arm64"
          elif [[ "${arch}" = "arm64" ]]; then
            export ARCH="arm64"
          else
            echo "Unsupported architecture: ${arch}"
            exit 1
          fi
          
          chmod a+x ${{ inputs.bin_path }}/${OS}-${ARCH}/fsm
          ln -s ${{ inputs.bin_path }}/${OS}-${ARCH}/fsm ${{ inputs.bin_path }}/fsm
          ls -l ${{ inputs.bin_path }}/fsm