name: Slash Commands
on:
  issue_comment:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute slash command
        if: steps.check.outputs.has-permission
        uses: wow-actions/slash-commands@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/slash-commands-config.yml